// // import 'package:freezed_annotation/freezed_annotation.dart';

// // // required: associates our `main.dart` with the code generated by Freezed
// // part 'user.freezed.dart';
// // // optional: Since our Person class is serializable, we must add this line.
// // // But if Person was not serializable, we could skip it.
// // part 'user.g.dart';

// // @freezed
// // abstract class User with _$User {
// //   const factory User({
// //     required String name,
// //     required int id,
// //     String? avatar,
// //   }) = _User;

// //   factory User.fromJson(Map<String, Object?> json) => _$UserFromJson(json);
// // }

// class User {
//   const User({
//     required String name,
//     required int id,
//     String? avatar,
//   }) : name = name,
//        id = id,
//        avatar = avatar;

//   final String name;
//   final int id;
//   final String? avatar;
// }
